### ISSUE TITLE
Error while setting 4th watchpoint

### ISSUE THREAD

**Issue by neanderthal148** [riscv/riscv-openocd#813] opened 2023-03-15 11:17 UTC
Hi,
I am getting an error when I try to set the 4th watchpoint using the wp command. I am able to set 4 breakpoints or a combination of 4 breakpoints and watchpoints but for some reason I cannot set 4 watchpoints.

![image](https://user-images.githubusercontent.com/49273085/225293039-891d347a-7657-49db-a7e0-59e5f89d4440.png)

**Comment by JanMatCodasip** [comment] 2023-03-15 15:04
Hi @neanderthal148, could you please provide us:

- commit ID from which you built your copy of `riscv-openocd`
- verbose debug log (start `openocd` with argument `-d3`)

Thank you!

**Comment by neanderthal148** [comment] 2023-03-16 10:19
Commit hash: d6bf022560d54f83bb7d73d5b1b9ae78cb5eaf11

[wp.debug.log](https://github.com/riscv/riscv-openocd/files/10989471/wp.debug.log)

**Comment by TommyMurphyTM1234** [comment] 2023-03-16 10:39
Also, what is the nature and provenance of the RISC-V implementation in your debug target?

**Comment by TommyMurphyTM1234** [comment] 2023-03-16 14:29
I've tried this using Spike as the debug target and can't reproduce the problem.
```
tommy@kingfisher:~/Downloads/sandbox$ telnet localhost 4444
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> wp 0x00 4 a
[riscv.cpu] Found 4 triggers
> wp 0x04 4 a
> wp 0x08 4 a
> wp 0x0c 4 a
> wp 0x10 4 a
can't add access watchpoint at 0x00000010, unrecognized error
Failure setting watchpoints

> wp
address: 0x00000000, len: 0x00000004, r/w/a: 2, value: 0x00000000, mask: 0xffffffff
address: 0x00000004, len: 0x00000004, r/w/a: 2, value: 0x00000000, mask: 0xffffffff
address: 0x00000008, len: 0x00000004, r/w/a: 2, value: 0x00000000, mask: 0xffffffff
address: 0x0000000c, len: 0x00000004, r/w/a: 2, value: 0x00000000, mask: 0xffffffff

> 
```

**Comment by TommyMurphyTM1234** [comment] 2023-03-16 17:24
In your log, the error arises here:
```
Error: 17293 239286 breakpoints.c:457 watchpoint_add_internal(): can't add access watchpoint at 0x00000020, unrecognized error
Error: 17294 239286 target.c:4160 handle_wp_command(): Failure setting watchpoints
Debug: 17295 239286 command.c:556 run_command(): Command 'wp' failed with error code -4
```
But I can't explain (or reproduce!) this so far.

If you can't easily debug OpenOCD for this issue then you may need to add some custom logging (e.g. to functions such as `find_trigger()`, `maybe_add_trigger_*()` etc.) to ascertain exactly what is going on/wrong.

**Comment by timsifive** [comment] 2023-03-17 00:19
You encounter a message like this one several times:
```
Debug: 8730 148571 riscv.c:523 set_trigger(): Trigger doesn't support what we need; After writing 0x28000000000010db to tdata1 it contains 0x280000000000105b; tdata1_ignore_mask=0x7e0000000000000
```

I don't see that message anywhere in the current source. Can you try building the latest riscv-openocd and share a log from that?

**Comment by TommyMurphyTM1234** [comment] 2023-03-26 11:42
Any update @neanderthal148?

**Comment by neanderthal148** [comment] 2023-03-27 09:03
Hi guys, thanks for the help. Issue seems to be solved after building the latest openocd

**Comment by TommyMurphyTM1234** [comment] 2023-03-27 16:49
Could you close the issue so @neanderthal148, please?

**Closed as completed** 2023-03-28 08:20 UTC
