### ISSUE TITLE
In debug mode, only one thread display stack info other threads dispaly 0  

### ISSUE THREAD

**Issue by paul5730** [riscv/riscv-openocd#584] opened 2021-03-11 09:23 UTC
As the title suggests,target chip belong to riscv , when the program runs to a breakpoint, only one thread displays the Stack Info.The other threads are 0 . as shown in the figure below
![image](https://user-images.githubusercontent.com/50826198/110764461-0e312200-828e-11eb-9174-4fb1db5a8fe4.png)

**Comment by JanMatCodasip** [comment] 2021-03-11 09:47
Hi @paul5730, 

from that very little information provided, I guess this is a single-hart RISC-V target running a FreeRTOS-based application. Am I correct?

FreeRTOS support has been commited to this riscv-openocd very recently (5 days ago in 50a5971be27ff11061776afc8014bbff22870b7c by @timsifive). Does your openocd build already include that change?

Jan

**Comment by paul5730** [comment] 2021-03-11 10:55
Hi JanMatCodasip 
JanMatCodasip : from that very little information provided, I guess this is a single-hart RISC-V target running a FreeRTOS-based application. Am I correct?
Paul5730: Yes, this is a single-hart RISC-V target , is it support for FreeRTOS thread awareness ?
JanMatCodasip : FreeRTOS support has been commited to this riscv-openocd very recently (5 days ago in 50a5971 by @timsifive). Does your openocd build already include that change?
Paul5730: Yes, I build already include that change.

**Comment by JanMatCodasip** [comment] 2021-03-11 11:32
I may not be able to help here due to limited time/knowledge, but if you'd like someone to take a look at this, please share a full verbose log from your OpenOCD: use argument `-d3`. Thanks.

**Comment by timsifive** [comment] 2021-03-11 18:14
I am actively working on the FreeRTOS support. It's definitely not complete yet. In fact I'm looking right now at a case where OpenOCD reports bad register values for the suspended threads.

**Comment by timsifive** [comment] 2021-03-17 21:36
Did you build your FreeRTOS binary using mainline FreeRTOS by any chance? It stores registers on the stack differently from how it works in the metal fork. :-(

If so, can you see if https://github.com/riscv/riscv-openocd/pull/586 works any better for you?

**Comment by en-sc** [comment] 2024-01-22 17:58
@paul5730, could you please check if the issue is still present? I would like to close it, but I do not have enough information to reproduce it and verify that it's fixed.

**Closed as not planned** 2024-01-26 13:41 UTC
