### ISSUE TITLE
Reverse commit 2ae0078fc that changes the error processing

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-openocd#171] opened 2018-01-04 20:39 UTC
This change affects other targets, and I doubt it can be upstreamed.

https://github.com/riscv/riscv-openocd/commit/2ae0078fc723d18822ed50f6f3accd32107acbef

In GNU MCU Eclipse OpenOCD I had to manually reverse these changes, in order to make it work again with ARM targets.

**Comment by timsifive** [comment] 2018-01-04 21:00
I'm working on some related code right now, and I'm considering making this behavior only active for RISC-V targets (and others that indicate they want it).

**Comment by timsifive** [comment] 2018-01-19 03:47
This is a duplicate of #115.

**Closed as completed by timsifive** 2018-01-19 03:47 UTC
