### ISSUE TITLE
Identify new hart on the fly

### ISSUE THREAD

**Issue by hananyasegal1** [riscv/riscv-openocd#849] opened 2023-05-15 12:33 UTC
Hi All,

I would like to ask if Openocd can identify a new hart after the initialization. 
For example if at init stage only hart0 is awaken and after some period of time during regular operation hart1 has been started, Can Openocd identify hart1?

Thanks,
Hananya

**Comment by JanMatCodasip** [comment] 2023-05-15 14:28
Hi @hananyasegal1,
OpenOCD needs to know about the existence of the target (hart) from the begining - it needs to be mentioned in the configuration.

However, if you know the hart will become available only later, the initial examination can be postponed by `-defer-examine` argument (documented here: https://openocd.org/doc/html/CPU-Configuration.html).

The examination of the hart can be triggered later manually by command `arp_examine`.

**Comment by hananyasegal1** [comment] 2023-05-15 14:45
Thanks for your detailed answer!

**Comment by hananyasegal1** [comment] 2023-05-15 14:47
Hi All,

One more question, if I want to change the Openocd source code itself, where is the preferred location to start with?

**Comment by timsifive** [comment] 2023-05-15 15:28
If your changes are only relevant to RISC-V targets, they should be made here. If they are more general, or in target-independent code, then ideally they are made upstream as described in https://github.com/riscv/riscv-openocd/blob/riscv/HACKING

**Comment by hananyasegal1** [comment] 2023-05-15 17:18
Hi Tim,

Thanks for your answer.
The targey is Riscv.
What do you mean 'here' in your answer?

Thanks,

**Comment by hananyasegal1** [comment] 2023-05-15 17:28
Hi Tim,

My question was where  is the recommended source code location to statt the invedtigation.

Thanks,
Hananya

**Comment by TommyMurphyTM1234** [comment] 2023-05-15 17:30
> Hi Tim,
> 
> Thanks for your answer. The targey is Riscv. What do you mean 'here' in your answer?
> 
> Thanks,

"Here" means this repository:

* https://github.com/riscv/riscv-openocd

As opposed to upstream:

* https://openocd.org/pages/repos.html

as described here:

* https://github.com/openocd-org/openocd/blob/master/HACKING

**Comment by hananyasegal1** [comment] 2023-05-15 17:57
Yes, I know.
Where do you think is the right place in the sourcecode  to start the investigation with?

**Comment by TommyMurphyTM1234** [comment] 2023-05-15 21:33
> Yes, I know. Where do you think is the right place in the sourcecode to start the investigation with?

@timsifive already answered this question above.

* https://github.com/riscv/riscv-openocd/issues/849#issuecomment-1548080885

If you mean what specific source file(s) then (again, as mentioned by @timsifive) that depends on the nature of the intended changes and whether they're completely RISC-V specific, in which case you will want to look here:

* https://github.com/riscv/riscv-openocd/tree/riscv/src/target/riscv

or if they involve more general, non RISC-V specific, target generic source code, in which case you'll maybe want to look here:

* https://github.com/riscv/riscv-openocd/tree/riscv/src/target

However, it's not really clear what precisely is the problem that you're trying to address, what changes this might involve, and why existing approaches such as outlined above by @JanMatCodasip using `-defer-examine` and `arp_examine` will not suffice without changes to OpenOCD.

* https://openocd.org/doc/html/CPU-Configuration.html

Your scenario, as briefly sketched in the original post, sounds a bit like the one mentioned here.

* https://github.com/riscv/riscv-openocd/issues/663

**Comment by hananyasegal1** [comment] 2023-05-16 05:20
Hi Tommy,

Thanks for your great answer.
The current solution is to actively send a command to Openocd to connect with command arp_examine. I want Openocd to do a scan in specific time interval or per step for example. I don't want that the user will type a specific command for this purpose.
One of the scenarios is: after reset only hart0 is awake and after some time hart0 wakes hart1. I want Openocd to identify it and connect to hart1 too.

**Comment by TommyMurphyTM1234** [comment] 2023-05-16 06:48
In my opinion, that sounds like something that might be implemented as a generic target feature - i.e. not specific to RISC-V harts, but available to other targets with cores in a similar configuration. In which case, it sounds like something that might be more suitable for discussion on the upstream OpenOCD development mailing list and implementation in the upstream source base:

* https://openocd.org/pages/mailing-lists.html
* https://openocd.org/pages/repos.html

**Comment by timsifive** [comment] 2023-05-16 16:33
> I want Openocd to do a scan in specific time interval or per step for example. I don't want that the user will type a specific command for this purpose.

You'll want to look at poll() code, and probably piggy-back onto that. The stuff in target.c might be a good starting point.

> One of the scenarios is: after reset only hart0 is awake and after some time hart0 wakes hart1. I want Openocd to identify it and connect to hart1 too.

I feel like this ought to work, if you put both harts in your config file. OpenOCD will definitely examine() RISC-V targets if they're not available when first connecting. I'm not sure if that will add them to gdb, though. That's much harder because gdb needs to know all the registers a hart has when you connect to gdb, and you can't know that until you examine the hart.

**Comment by hananyasegal1** [comment] 2023-05-16 18:26
Thank you very much for your detailed answer. It helps me a lot. I'll carfully look at it.

**Comment by en-sc** [comment] 2024-01-22 19:12
@hananyasegal1, seems like the issue is resolved. Can I close it?

**Closed as not planned** 2024-01-26 13:46 UTC
